name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
version-template: "$MAJOR.$MINOR.$PATCH"
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
  - title: '📃 Documentation'
    label: 'documentation'
  - title: '🔬 Others'
    labels:
      - 'refactor'
      - 'test'
      - 'ci'
change-template: |
  - $TITLE @$AUTHOR (#$NUMBER) - [$BASE_REF_NAME <- $HEAD_REF_NAME]
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
    title:
      - '/docs:/i'
    branch:
      - '/doc{0,1}\/.+/'
  - label: 'fix'
    branch:
      - '/fix\/.+/'
      - '/bug\/.+/'
      - '/bugfix\/.+/'
      - '/hotfix\/.+/'
    title:
      - '/fix/i'
  - label: 'feature'
    branch:
      - '/feature\/.+/'
    title:
      - '/feat:/i'
  - label: 'refactor'
    branch: 
      - '/refactor\/.+/'
    title:
      - '/refactor:/i'
  - label: 'ci'
    title:
      - '/ci:/i'
  - label: 'test'
    title:
      - '/test:/i'
  - label: 'major'
    body: 
      - '(?i)\[\s*x\s*\] major'

      
commitish: main

template: |
  ## Version changelog: $RESOLVED_VERSION

  ### Merged changes
    $CHANGES
