# .github/release-drafter.develop.yml
name-template: 'Develop Release $DATE'
tag-template: 'develop-$DATE'
version-template: "$DATE"

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
