name: "Publish Tag on Release Publish"

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  publish_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create and Push New Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag ${{ github.event.release.tag_name }}
          git push origin ${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
