name: "Release Drafter Test"

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, reopened, synchronize]
jobs:
  release_drafter:
    permissions:
        contents: write
        pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update Release Draft with Release Drafter
        id: release
        uses: release-drafter/release-drafter@v6
        with:
          # You can configure Release Drafter here with a custom config file if needed
          config-name: 'release-drafter.yml'
          commitish: main
          # publish: true #sd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} #TEST
