name: "Release Drafter Test"

on:
    push:
        branches:
        - main
    pull_request:
        # pull_request event is required only for autolabeler
        types: [opened, reopened, synchronize]

jobs:
  release_drafter:
    permissions:
        contents: write
        pull-requests: write
        id-token: write
        issues: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update Release Draft with Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
          # You can configure Release Drafter here with a custom config file if needed
          config-name: 'release-drafter.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} #TEST